# Generated by Django 5.0.6 on 2025-03-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='authors',
            new_name='author',
        ),
    ]
